// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/battery.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiInitInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -1878742325;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_battery_app',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Caps crateApiBatteryBatteryConnCapabilities({required BatteryConn that});

  DeviceInfo crateApiBatteryBatteryConnInfo({required BatteryConn that});

  Future<void> crateApiBatteryBatteryConnSet({
    required BatteryConn that,
    required String id,
    required String value,
  });

  Future<BatteryStatus> crateApiBatteryBatteryConnStatus({
    required BatteryConn that,
  });

  Future<void> crateApiBatteryBatteryConnToggle({
    required BatteryConn that,
    required String id,
    required bool on_,
  });

  Future<BatteryConn> crateApiBatteryConnect({
    required String query,
    required BigInt bleSecs,
  });

  Future<List<DiscoveredDevice>> crateApiBatteryDiscoverDevices({
    required BigInt bleSecs,
    required bool probeSerial,
  });

  bool crateApiBatteryHasSerialSupport();

  Future<void> crateApiInitInitApp();

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_BatteryConn;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_BatteryConn;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_BatteryConnPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Caps crateApiBatteryBatteryConnCapabilities({required BatteryConn that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBatteryConn(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_caps,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBatteryBatteryConnCapabilitiesConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBatteryBatteryConnCapabilitiesConstMeta =>
      const TaskConstMeta(
        debugName: "BatteryConn_capabilities",
        argNames: ["that"],
      );

  @override
  DeviceInfo crateApiBatteryBatteryConnInfo({required BatteryConn that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBatteryConn(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_device_info,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBatteryBatteryConnInfoConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBatteryBatteryConnInfoConstMeta =>
      const TaskConstMeta(debugName: "BatteryConn_info", argNames: ["that"]);

  @override
  Future<void> crateApiBatteryBatteryConnSet({
    required BatteryConn that,
    required String id,
    required String value,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBatteryConn(
            that,
            serializer,
          );
          sse_encode_String(id, serializer);
          sse_encode_String(value, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBatteryBatteryConnSetConstMeta,
        argValues: [that, id, value],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBatteryBatteryConnSetConstMeta =>
      const TaskConstMeta(
        debugName: "BatteryConn_set",
        argNames: ["that", "id", "value"],
      );

  @override
  Future<BatteryStatus> crateApiBatteryBatteryConnStatus({
    required BatteryConn that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBatteryConn(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_battery_status,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBatteryBatteryConnStatusConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBatteryBatteryConnStatusConstMeta =>
      const TaskConstMeta(debugName: "BatteryConn_status", argNames: ["that"]);

  @override
  Future<void> crateApiBatteryBatteryConnToggle({
    required BatteryConn that,
    required String id,
    required bool on_,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBatteryConn(
            that,
            serializer,
          );
          sse_encode_String(id, serializer);
          sse_encode_bool(on_, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBatteryBatteryConnToggleConstMeta,
        argValues: [that, id, on_],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBatteryBatteryConnToggleConstMeta =>
      const TaskConstMeta(
        debugName: "BatteryConn_toggle",
        argNames: ["that", "id", "on_"],
      );

  @override
  Future<BatteryConn> crateApiBatteryConnect({
    required String query,
    required BigInt bleSecs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(query, serializer);
          sse_encode_u_64(bleSecs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBatteryConn,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBatteryConnectConstMeta,
        argValues: [query, bleSecs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBatteryConnectConstMeta =>
      const TaskConstMeta(debugName: "connect", argNames: ["query", "bleSecs"]);

  @override
  Future<List<DiscoveredDevice>> crateApiBatteryDiscoverDevices({
    required BigInt bleSecs,
    required bool probeSerial,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(bleSecs, serializer);
          sse_encode_bool(probeSerial, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_discovered_device,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiBatteryDiscoverDevicesConstMeta,
        argValues: [bleSecs, probeSerial],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBatteryDiscoverDevicesConstMeta =>
      const TaskConstMeta(
        debugName: "discover_devices",
        argNames: ["bleSecs", "probeSerial"],
      );

  @override
  bool crateApiBatteryHasSerialSupport() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBatteryHasSerialSupportConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBatteryHasSerialSupportConstMeta =>
      const TaskConstMeta(debugName: "has_serial_support", argNames: []);

  @override
  Future<void> crateApiInitInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_BatteryConn => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBatteryConn;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_BatteryConn => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBatteryConn;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  BatteryConn
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBatteryConn(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return BatteryConnImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  BatteryConn
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBatteryConn(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return BatteryConnImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  BatteryConn
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBatteryConn(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return BatteryConnImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  BatteryStatus dco_decode_battery_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 23)
      throw Exception('unexpected arr length: expect 23 but see ${arr.length}');
    return BatteryStatus(
      soc: dco_decode_opt_box_autoadd_f_32(arr[0]),
      soh: dco_decode_opt_box_autoadd_f_32(arr[1]),
      voltage: dco_decode_opt_box_autoadd_f_32(arr[2]),
      current: dco_decode_opt_box_autoadd_f_32(arr[3]),
      powerIn: dco_decode_opt_box_autoadd_f_32(arr[4]),
      powerOut: dco_decode_opt_box_autoadd_f_32(arr[5]),
      temperatures: dco_decode_list_sensor(arr[6]),
      timeRemainingH: dco_decode_opt_box_autoadd_f_32(arr[7]),
      capacityRemainingAh: dco_decode_opt_box_autoadd_f_32(arr[8]),
      capacityFullAh: dco_decode_opt_box_autoadd_f_32(arr[9]),
      cycles: dco_decode_opt_box_autoadd_u_32(arr[10]),
      charging: dco_decode_opt_box_autoadd_bool(arr[11]),
      discharging: dco_decode_opt_box_autoadd_bool(arr[12]),
      switches: dco_decode_list_switch(arr[13]),
      chargeCurrentLimitA: dco_decode_opt_box_autoadd_f_32(arr[14]),
      dischargeCurrentLimitA: dco_decode_opt_box_autoadd_f_32(arr[15]),
      socLimitMax: dco_decode_opt_box_autoadd_f_32(arr[16]),
      socLimitMin: dco_decode_opt_box_autoadd_f_32(arr[17]),
      cells: dco_decode_list_cell_info(arr[18]),
      ports: dco_decode_list_port_info(arr[19]),
      alarms: dco_decode_list_String(arr[20]),
      temperatureC: dco_decode_opt_box_autoadd_f_32(arr[21]),
      cellDelta: dco_decode_opt_box_autoadd_f_32(arr[22]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  double dco_decode_box_autoadd_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  PortDirection dco_decode_box_autoadd_port_direction(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_port_direction(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  Caps dco_decode_caps(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 13)
      throw Exception('unexpected arr length: expect 13 but see ${arr.length}');
    return Caps(
      readBasic: dco_decode_bool(arr[0]),
      readCells: dco_decode_bool(arr[1]),
      readPorts: dco_decode_bool(arr[2]),
      readTemperature: dco_decode_bool(arr[3]),
      readLimits: dco_decode_bool(arr[4]),
      readAlarms: dco_decode_bool(arr[5]),
      togglePorts: dco_decode_bool(arr[6]),
      toggleCharge: dco_decode_bool(arr[7]),
      toggleDischarge: dco_decode_bool(arr[8]),
      toggleBalancer: dco_decode_bool(arr[9]),
      setChargeLimit: dco_decode_bool(arr[10]),
      writeSettings: dco_decode_bool(arr[11]),
      controllable: dco_decode_bool(arr[12]),
    );
  }

  @protected
  CellInfo dco_decode_cell_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return CellInfo(
      index: dco_decode_u_8(arr[0]),
      voltage: dco_decode_opt_box_autoadd_f_32(arr[1]),
      resistance: dco_decode_opt_box_autoadd_f_32(arr[2]),
      balancing: dco_decode_opt_box_autoadd_bool(arr[3]),
    );
  }

  @protected
  DeviceClass dco_decode_device_class(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return DeviceClass.values[raw as int];
  }

  @protected
  DeviceInfo dco_decode_device_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return DeviceInfo(
      backend: dco_decode_String(arr[0]),
      model: dco_decode_opt_String(arr[1]),
      serial: dco_decode_opt_String(arr[2]),
      firmware: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  DiscoveredDevice dco_decode_discovered_device(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return DiscoveredDevice(
      id: dco_decode_String(arr[0]),
      label: dco_decode_String(arr[1]),
      backend: dco_decode_String(arr[2]),
      class_: dco_decode_device_class(arr[3]),
    );
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<CellInfo> dco_decode_list_cell_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_cell_info).toList();
  }

  @protected
  List<DiscoveredDevice> dco_decode_list_discovered_device(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_discovered_device).toList();
  }

  @protected
  List<PortInfo> dco_decode_list_port_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_port_info).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<Sensor> dco_decode_list_sensor(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_sensor).toList();
  }

  @protected
  List<Switch> dco_decode_list_switch(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_switch).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_bool(raw);
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_32(raw);
  }

  @protected
  PortDirection? dco_decode_opt_box_autoadd_port_direction(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_port_direction(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  PortDirection dco_decode_port_direction(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return PortDirection.values[raw as int];
  }

  @protected
  PortInfo dco_decode_port_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return PortInfo(
      id: dco_decode_String(arr[0]),
      label: dco_decode_opt_String(arr[1]),
      direction: dco_decode_opt_box_autoadd_port_direction(arr[2]),
      on_: dco_decode_opt_box_autoadd_bool(arr[3]),
      watts: dco_decode_opt_box_autoadd_f_32(arr[4]),
    );
  }

  @protected
  Sensor dco_decode_sensor(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return Sensor(
      id: dco_decode_String(arr[0]),
      label: dco_decode_opt_String(arr[1]),
      celsius: dco_decode_f_32(arr[2]),
    );
  }

  @protected
  Switch dco_decode_switch(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return Switch(
      id: dco_decode_String(arr[0]),
      label: dco_decode_opt_String(arr[1]),
      on_: dco_decode_bool(arr[2]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  BatteryConn
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBatteryConn(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return BatteryConnImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  BatteryConn
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBatteryConn(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return BatteryConnImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  BatteryConn
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBatteryConn(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return BatteryConnImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  BatteryStatus sse_decode_battery_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_soc = sse_decode_opt_box_autoadd_f_32(deserializer);
    var var_soh = sse_decode_opt_box_autoadd_f_32(deserializer);
    var var_voltage = sse_decode_opt_box_autoadd_f_32(deserializer);
    var var_current = sse_decode_opt_box_autoadd_f_32(deserializer);
    var var_powerIn = sse_decode_opt_box_autoadd_f_32(deserializer);
    var var_powerOut = sse_decode_opt_box_autoadd_f_32(deserializer);
    var var_temperatures = sse_decode_list_sensor(deserializer);
    var var_timeRemainingH = sse_decode_opt_box_autoadd_f_32(deserializer);
    var var_capacityRemainingAh = sse_decode_opt_box_autoadd_f_32(deserializer);
    var var_capacityFullAh = sse_decode_opt_box_autoadd_f_32(deserializer);
    var var_cycles = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_charging = sse_decode_opt_box_autoadd_bool(deserializer);
    var var_discharging = sse_decode_opt_box_autoadd_bool(deserializer);
    var var_switches = sse_decode_list_switch(deserializer);
    var var_chargeCurrentLimitA = sse_decode_opt_box_autoadd_f_32(deserializer);
    var var_dischargeCurrentLimitA = sse_decode_opt_box_autoadd_f_32(
      deserializer,
    );
    var var_socLimitMax = sse_decode_opt_box_autoadd_f_32(deserializer);
    var var_socLimitMin = sse_decode_opt_box_autoadd_f_32(deserializer);
    var var_cells = sse_decode_list_cell_info(deserializer);
    var var_ports = sse_decode_list_port_info(deserializer);
    var var_alarms = sse_decode_list_String(deserializer);
    var var_temperatureC = sse_decode_opt_box_autoadd_f_32(deserializer);
    var var_cellDelta = sse_decode_opt_box_autoadd_f_32(deserializer);
    return BatteryStatus(
      soc: var_soc,
      soh: var_soh,
      voltage: var_voltage,
      current: var_current,
      powerIn: var_powerIn,
      powerOut: var_powerOut,
      temperatures: var_temperatures,
      timeRemainingH: var_timeRemainingH,
      capacityRemainingAh: var_capacityRemainingAh,
      capacityFullAh: var_capacityFullAh,
      cycles: var_cycles,
      charging: var_charging,
      discharging: var_discharging,
      switches: var_switches,
      chargeCurrentLimitA: var_chargeCurrentLimitA,
      dischargeCurrentLimitA: var_dischargeCurrentLimitA,
      socLimitMax: var_socLimitMax,
      socLimitMin: var_socLimitMin,
      cells: var_cells,
      ports: var_ports,
      alarms: var_alarms,
      temperatureC: var_temperatureC,
      cellDelta: var_cellDelta,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_bool(deserializer));
  }

  @protected
  double sse_decode_box_autoadd_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_32(deserializer));
  }

  @protected
  PortDirection sse_decode_box_autoadd_port_direction(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_port_direction(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  Caps sse_decode_caps(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_readBasic = sse_decode_bool(deserializer);
    var var_readCells = sse_decode_bool(deserializer);
    var var_readPorts = sse_decode_bool(deserializer);
    var var_readTemperature = sse_decode_bool(deserializer);
    var var_readLimits = sse_decode_bool(deserializer);
    var var_readAlarms = sse_decode_bool(deserializer);
    var var_togglePorts = sse_decode_bool(deserializer);
    var var_toggleCharge = sse_decode_bool(deserializer);
    var var_toggleDischarge = sse_decode_bool(deserializer);
    var var_toggleBalancer = sse_decode_bool(deserializer);
    var var_setChargeLimit = sse_decode_bool(deserializer);
    var var_writeSettings = sse_decode_bool(deserializer);
    var var_controllable = sse_decode_bool(deserializer);
    return Caps(
      readBasic: var_readBasic,
      readCells: var_readCells,
      readPorts: var_readPorts,
      readTemperature: var_readTemperature,
      readLimits: var_readLimits,
      readAlarms: var_readAlarms,
      togglePorts: var_togglePorts,
      toggleCharge: var_toggleCharge,
      toggleDischarge: var_toggleDischarge,
      toggleBalancer: var_toggleBalancer,
      setChargeLimit: var_setChargeLimit,
      writeSettings: var_writeSettings,
      controllable: var_controllable,
    );
  }

  @protected
  CellInfo sse_decode_cell_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_index = sse_decode_u_8(deserializer);
    var var_voltage = sse_decode_opt_box_autoadd_f_32(deserializer);
    var var_resistance = sse_decode_opt_box_autoadd_f_32(deserializer);
    var var_balancing = sse_decode_opt_box_autoadd_bool(deserializer);
    return CellInfo(
      index: var_index,
      voltage: var_voltage,
      resistance: var_resistance,
      balancing: var_balancing,
    );
  }

  @protected
  DeviceClass sse_decode_device_class(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return DeviceClass.values[inner];
  }

  @protected
  DeviceInfo sse_decode_device_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_backend = sse_decode_String(deserializer);
    var var_model = sse_decode_opt_String(deserializer);
    var var_serial = sse_decode_opt_String(deserializer);
    var var_firmware = sse_decode_opt_String(deserializer);
    return DeviceInfo(
      backend: var_backend,
      model: var_model,
      serial: var_serial,
      firmware: var_firmware,
    );
  }

  @protected
  DiscoveredDevice sse_decode_discovered_device(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_label = sse_decode_String(deserializer);
    var var_backend = sse_decode_String(deserializer);
    var var_class_ = sse_decode_device_class(deserializer);
    return DiscoveredDevice(
      id: var_id,
      label: var_label,
      backend: var_backend,
      class_: var_class_,
    );
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<CellInfo> sse_decode_list_cell_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <CellInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_cell_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<DiscoveredDevice> sse_decode_list_discovered_device(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <DiscoveredDevice>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_discovered_device(deserializer));
    }
    return ans_;
  }

  @protected
  List<PortInfo> sse_decode_list_port_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PortInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_port_info(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<Sensor> sse_decode_list_sensor(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Sensor>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_sensor(deserializer));
    }
    return ans_;
  }

  @protected
  List<Switch> sse_decode_list_switch(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Switch>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_switch(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_bool(deserializer));
    } else {
      return null;
    }
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PortDirection? sse_decode_opt_box_autoadd_port_direction(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_port_direction(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PortDirection sse_decode_port_direction(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return PortDirection.values[inner];
  }

  @protected
  PortInfo sse_decode_port_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_label = sse_decode_opt_String(deserializer);
    var var_direction = sse_decode_opt_box_autoadd_port_direction(deserializer);
    var var_on_ = sse_decode_opt_box_autoadd_bool(deserializer);
    var var_watts = sse_decode_opt_box_autoadd_f_32(deserializer);
    return PortInfo(
      id: var_id,
      label: var_label,
      direction: var_direction,
      on_: var_on_,
      watts: var_watts,
    );
  }

  @protected
  Sensor sse_decode_sensor(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_label = sse_decode_opt_String(deserializer);
    var var_celsius = sse_decode_f_32(deserializer);
    return Sensor(id: var_id, label: var_label, celsius: var_celsius);
  }

  @protected
  Switch sse_decode_switch(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_label = sse_decode_opt_String(deserializer);
    var var_on_ = sse_decode_bool(deserializer);
    return Switch(id: var_id, label: var_label, on_: var_on_);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBatteryConn(
    BatteryConn self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as BatteryConnImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBatteryConn(
    BatteryConn self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as BatteryConnImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBatteryConn(
    BatteryConn self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as BatteryConnImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_battery_status(BatteryStatus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_f_32(self.soc, serializer);
    sse_encode_opt_box_autoadd_f_32(self.soh, serializer);
    sse_encode_opt_box_autoadd_f_32(self.voltage, serializer);
    sse_encode_opt_box_autoadd_f_32(self.current, serializer);
    sse_encode_opt_box_autoadd_f_32(self.powerIn, serializer);
    sse_encode_opt_box_autoadd_f_32(self.powerOut, serializer);
    sse_encode_list_sensor(self.temperatures, serializer);
    sse_encode_opt_box_autoadd_f_32(self.timeRemainingH, serializer);
    sse_encode_opt_box_autoadd_f_32(self.capacityRemainingAh, serializer);
    sse_encode_opt_box_autoadd_f_32(self.capacityFullAh, serializer);
    sse_encode_opt_box_autoadd_u_32(self.cycles, serializer);
    sse_encode_opt_box_autoadd_bool(self.charging, serializer);
    sse_encode_opt_box_autoadd_bool(self.discharging, serializer);
    sse_encode_list_switch(self.switches, serializer);
    sse_encode_opt_box_autoadd_f_32(self.chargeCurrentLimitA, serializer);
    sse_encode_opt_box_autoadd_f_32(self.dischargeCurrentLimitA, serializer);
    sse_encode_opt_box_autoadd_f_32(self.socLimitMax, serializer);
    sse_encode_opt_box_autoadd_f_32(self.socLimitMin, serializer);
    sse_encode_list_cell_info(self.cells, serializer);
    sse_encode_list_port_info(self.ports, serializer);
    sse_encode_list_String(self.alarms, serializer);
    sse_encode_opt_box_autoadd_f_32(self.temperatureC, serializer);
    sse_encode_opt_box_autoadd_f_32(self.cellDelta, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_port_direction(
    PortDirection self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_port_direction(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_caps(Caps self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.readBasic, serializer);
    sse_encode_bool(self.readCells, serializer);
    sse_encode_bool(self.readPorts, serializer);
    sse_encode_bool(self.readTemperature, serializer);
    sse_encode_bool(self.readLimits, serializer);
    sse_encode_bool(self.readAlarms, serializer);
    sse_encode_bool(self.togglePorts, serializer);
    sse_encode_bool(self.toggleCharge, serializer);
    sse_encode_bool(self.toggleDischarge, serializer);
    sse_encode_bool(self.toggleBalancer, serializer);
    sse_encode_bool(self.setChargeLimit, serializer);
    sse_encode_bool(self.writeSettings, serializer);
    sse_encode_bool(self.controllable, serializer);
  }

  @protected
  void sse_encode_cell_info(CellInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_8(self.index, serializer);
    sse_encode_opt_box_autoadd_f_32(self.voltage, serializer);
    sse_encode_opt_box_autoadd_f_32(self.resistance, serializer);
    sse_encode_opt_box_autoadd_bool(self.balancing, serializer);
  }

  @protected
  void sse_encode_device_class(DeviceClass self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_device_info(DeviceInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.backend, serializer);
    sse_encode_opt_String(self.model, serializer);
    sse_encode_opt_String(self.serial, serializer);
    sse_encode_opt_String(self.firmware, serializer);
  }

  @protected
  void sse_encode_discovered_device(
    DiscoveredDevice self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.label, serializer);
    sse_encode_String(self.backend, serializer);
    sse_encode_device_class(self.class_, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_cell_info(
    List<CellInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_cell_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_discovered_device(
    List<DiscoveredDevice> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_discovered_device(item, serializer);
    }
  }

  @protected
  void sse_encode_list_port_info(
    List<PortInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_port_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_sensor(List<Sensor> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_sensor(item, serializer);
    }
  }

  @protected
  void sse_encode_list_switch(List<Switch> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_switch(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_bool(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_32(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_port_direction(
    PortDirection? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_port_direction(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_port_direction(PortDirection self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_port_info(PortInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_opt_String(self.label, serializer);
    sse_encode_opt_box_autoadd_port_direction(self.direction, serializer);
    sse_encode_opt_box_autoadd_bool(self.on_, serializer);
    sse_encode_opt_box_autoadd_f_32(self.watts, serializer);
  }

  @protected
  void sse_encode_sensor(Sensor self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_opt_String(self.label, serializer);
    sse_encode_f_32(self.celsius, serializer);
  }

  @protected
  void sse_encode_switch(Switch self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_opt_String(self.label, serializer);
    sse_encode_bool(self.on_, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class BatteryConnImpl extends RustOpaque implements BatteryConn {
  // Not to be used by end users
  BatteryConnImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  BatteryConnImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_BatteryConn,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_BatteryConn,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_BatteryConnPtr,
  );

  Caps capabilities() =>
      RustLib.instance.api.crateApiBatteryBatteryConnCapabilities(that: this);

  DeviceInfo info() =>
      RustLib.instance.api.crateApiBatteryBatteryConnInfo(that: this);

  /// Set a named value (`"charge_limit"` = `"80"`, ...).
  Future<void> set_({required String id, required String value}) => RustLib
      .instance
      .api
      .crateApiBatteryBatteryConnSet(that: this, id: id, value: value);

  /// Fetch a fresh status snapshot.
  Future<BatteryStatus> status() =>
      RustLib.instance.api.crateApiBatteryBatteryConnStatus(that: this);

  /// Toggle a port or switch by id (`"ac"`, `"charging"`, `"heater"`, ...).
  Future<void> toggle({required String id, required bool on_}) => RustLib
      .instance
      .api
      .crateApiBatteryBatteryConnToggle(that: this, id: id, on_: on_);
}
