// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'battery.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `actor`, `command`, `from_ref`, `publish`, `run_cmd`, `shutdown`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CmdMsg`, `Wake`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

/// Scan all enabled transports. `probe_serial` is ignored on platforms
/// without serial backends.
Future<List<DiscoveredDevice>> discoverDevices({
  required BigInt bleSecs,
  required bool probeSerial,
}) => RustLib.instance.api.crateApiBatteryDiscoverDevices(
  bleSecs: bleSecs,
  probeSerial: probeSerial,
);

/// Connect to a device from the last `discover_devices` call, by id (or
/// unambiguous prefix / label substring — same resolution as the CLI).
Future<BatteryConn> connect({required String query, required BigInt bleSecs}) =>
    RustLib.instance.api.crateApiBatteryConnect(query: query, bleSecs: bleSecs);

/// True when this build can probe serial ports (desktop targets).
bool hasSerialSupport() =>
    RustLib.instance.api.crateApiBatteryHasSerialSupport();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BatteryConn>>
abstract class BatteryConn implements RustOpaqueInterface {
  Caps capabilities();

  DeviceInfo info();

  /// Set a named value (`"charge_limit"` = `"80"`, ...).
  Future<void> set_({required String id, required String value});

  /// Current full snapshot the actor has accumulated. Used for
  /// manual/pull-to-refresh; the live picture comes from [`watch`](Self::watch).
  BatteryStatus status();

  /// Toggle a port or switch by id (`"ac"`, `"charging"`, `"heater"`, ...).
  Future<void> toggle({required String id, required bool on_});

  /// Subscribe to the **real-time** stream. The first event is a full
  /// [`StreamEvent::Snapshot`] of current state; subsequent events are
  /// incremental [`StreamEvent::Update`]s (or [`StreamEvent::Error`]). Ends
  /// when Dart cancels the subscription.
  Stream<StreamEvent> watch();
}

/// A snapshot of device state: free-form, id-addressed collections.
class BatteryStatus {
  final List<Sensor> sensors;
  final List<Switch> switches;
  final List<PortInfo> ports;
  final List<CellInfo> cells;
  final List<Setting> settings;
  final List<String> alarms;

  const BatteryStatus({
    required this.sensors,
    required this.switches,
    required this.ports,
    required this.cells,
    required this.settings,
    required this.alarms,
  });

  @override
  int get hashCode =>
      sensors.hashCode ^
      switches.hashCode ^
      ports.hashCode ^
      cells.hashCode ^
      settings.hashCode ^
      alarms.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BatteryStatus &&
          runtimeType == other.runtimeType &&
          sensors == other.sensors &&
          switches == other.switches &&
          ports == other.ports &&
          cells == other.cells &&
          settings == other.settings &&
          alarms == other.alarms;
}

/// Flattened capability flags (Dart-friendly booleans).
class Caps {
  final bool readBasic;
  final bool readCells;
  final bool readPorts;
  final bool readTemperature;
  final bool readLimits;
  final bool readAlarms;
  final bool toggleCharge;
  final bool toggleDischarge;
  final bool toggleBalancer;
  final bool setChargeLimit;
  final bool writeSettings;
  final bool controllable;

  const Caps({
    required this.readBasic,
    required this.readCells,
    required this.readPorts,
    required this.readTemperature,
    required this.readLimits,
    required this.readAlarms,
    required this.toggleCharge,
    required this.toggleDischarge,
    required this.toggleBalancer,
    required this.setChargeLimit,
    required this.writeSettings,
    required this.controllable,
  });

  @override
  int get hashCode =>
      readBasic.hashCode ^
      readCells.hashCode ^
      readPorts.hashCode ^
      readTemperature.hashCode ^
      readLimits.hashCode ^
      readAlarms.hashCode ^
      toggleCharge.hashCode ^
      toggleDischarge.hashCode ^
      toggleBalancer.hashCode ^
      setChargeLimit.hashCode ^
      writeSettings.hashCode ^
      controllable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Caps &&
          runtimeType == other.runtimeType &&
          readBasic == other.readBasic &&
          readCells == other.readCells &&
          readPorts == other.readPorts &&
          readTemperature == other.readTemperature &&
          readLimits == other.readLimits &&
          readAlarms == other.readAlarms &&
          toggleCharge == other.toggleCharge &&
          toggleDischarge == other.toggleDischarge &&
          toggleBalancer == other.toggleBalancer &&
          setChargeLimit == other.setChargeLimit &&
          writeSettings == other.writeSettings &&
          controllable == other.controllable;
}

class CellInfo {
  final int index;
  final double? voltage;
  final double? resistance;
  final bool? balancing;

  const CellInfo({
    required this.index,
    this.voltage,
    this.resistance,
    this.balancing,
  });

  @override
  int get hashCode =>
      index.hashCode ^
      voltage.hashCode ^
      resistance.hashCode ^
      balancing.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CellInfo &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          voltage == other.voltage &&
          resistance == other.resistance &&
          balancing == other.balancing;
}

enum DeviceClass { bms, powerStation, monitor }

class DeviceInfo {
  final String backend;
  final String? model;
  final String? serial;
  final String? firmware;

  const DeviceInfo({
    required this.backend,
    this.model,
    this.serial,
    this.firmware,
  });

  @override
  int get hashCode =>
      backend.hashCode ^ model.hashCode ^ serial.hashCode ^ firmware.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceInfo &&
          runtimeType == other.runtimeType &&
          backend == other.backend &&
          model == other.model &&
          serial == other.serial &&
          firmware == other.firmware;
}

class DiscoveredDevice {
  final String id;
  final String label;
  final String backend;
  final DeviceClass class_;

  const DiscoveredDevice({
    required this.id,
    required this.label,
    required this.backend,
    required this.class_,
  });

  @override
  int get hashCode =>
      id.hashCode ^ label.hashCode ^ backend.hashCode ^ class_.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiscoveredDevice &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          backend == other.backend &&
          class_ == other.class_;
}

enum PortDirection { in_, out, bidir }

class PortInfo {
  final String id;
  final String? label;
  final PortDirection? direction;
  final bool? on_;
  final double? watts;

  /// Whether this specific port accepts on/off control.
  final bool settable;

  const PortInfo({
    required this.id,
    this.label,
    this.direction,
    this.on_,
    this.watts,
    required this.settable,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      label.hashCode ^
      direction.hashCode ^
      on_.hashCode ^
      watts.hashCode ^
      settable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PortInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          direction == other.direction &&
          on_ == other.on_ &&
          watts == other.watts &&
          settable == other.settable;
}

/// A read-only scalar reading (SOC, voltage, a temperature probe, ...).
class Sensor {
  final String id;
  final String? label;
  final double value;
  final SensorUnit unit;

  const Sensor({
    required this.id,
    this.label,
    required this.value,
    required this.unit,
  });

  @override
  int get hashCode =>
      id.hashCode ^ label.hashCode ^ value.hashCode ^ unit.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Sensor &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          value == other.value &&
          unit == other.unit;
}

/// Physical unit of a [`Sensor`]/numeric setting.
enum SensorUnit {
  percent,
  volt,
  amp,
  watt,
  celsius,
  ampHour,
  hour,
  second,
  count,
}

/// A readable/writable configuration value (BMS thresholds, charge limits, ...).
class Setting {
  final String id;
  final String? label;
  final SettingValue value;
  final SettingKind kind;
  final bool writable;

  const Setting({
    required this.id,
    this.label,
    required this.value,
    required this.kind,
    required this.writable,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      label.hashCode ^
      value.hashCode ^
      kind.hashCode ^
      writable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Setting &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          value == other.value &&
          kind == other.kind &&
          writable == other.writable;
}

@freezed
sealed class SettingKind with _$SettingKind {
  const SettingKind._();

  const factory SettingKind.bool() = SettingKind_Bool;

  /// `unit` is a display symbol (e.g. `"V"`, `"%"`), empty for none.
  const factory SettingKind.number({
    double? min,
    double? max,
    double? step,
    required String unit,
  }) = SettingKind_Number;
  const factory SettingKind.enum_({required List<String> options}) =
      SettingKind_Enum;
  const factory SettingKind.text() = SettingKind_Text;
}

@freezed
sealed class SettingValue with _$SettingValue {
  const SettingValue._();

  const factory SettingValue.bool(bool field0) = SettingValue_Bool;
  const factory SettingValue.number(double field0) = SettingValue_Number;
  const factory SettingValue.text(String field0) = SettingValue_Text;
}

@freezed
sealed class StatusUpdate with _$StatusUpdate {
  const StatusUpdate._();

  const factory StatusUpdate.sensor(Sensor field0) = StatusUpdate_Sensor;
  const factory StatusUpdate.switch_(Switch field0) = StatusUpdate_Switch;
  const factory StatusUpdate.port(PortInfo field0) = StatusUpdate_Port;
  const factory StatusUpdate.cell(CellInfo field0) = StatusUpdate_Cell;
  const factory StatusUpdate.setting(Setting field0) = StatusUpdate_Setting;
  const factory StatusUpdate.alarms(List<String> field0) = StatusUpdate_Alarms;
}

@freezed
sealed class StreamEvent with _$StreamEvent {
  const StreamEvent._();

  /// Full state; sent once when a subscriber attaches (and after a lag resync).
  const factory StreamEvent.snapshot(BatteryStatus field0) =
      StreamEvent_Snapshot;

  /// A single incremental change.
  const factory StreamEvent.update(StatusUpdate field0) = StreamEvent_Update;

  /// A transient transport error.
  const factory StreamEvent.error(String field0) = StreamEvent_Error;
}

/// A writable boolean (charge/discharge MOSFET, heater, ...).
class Switch {
  final String id;
  final String? label;
  final bool on_;

  const Switch({required this.id, this.label, required this.on_});

  @override
  int get hashCode => id.hashCode ^ label.hashCode ^ on_.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Switch &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          on_ == other.on_;
}
