// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `from_ref`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `from`, `from`, `from`

/// Scan all enabled transports. `probe_serial` is ignored on platforms
/// without serial backends.
Future<List<DiscoveredDevice>> discoverDevices({
  required BigInt bleSecs,
  required bool probeSerial,
}) => RustLib.instance.api.crateApiBatteryDiscoverDevices(
  bleSecs: bleSecs,
  probeSerial: probeSerial,
);

/// Connect to a device from the last `discover_devices` call, by id (or
/// unambiguous prefix / label substring — same resolution as the CLI).
Future<BatteryConn> connect({required String query, required BigInt bleSecs}) =>
    RustLib.instance.api.crateApiBatteryConnect(query: query, bleSecs: bleSecs);

/// True when this build can probe serial ports (desktop targets).
bool hasSerialSupport() =>
    RustLib.instance.api.crateApiBatteryHasSerialSupport();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BatteryConn>>
abstract class BatteryConn implements RustOpaqueInterface {
  Caps capabilities();

  DeviceInfo info();

  /// Set a named value (`"charge_limit"` = `"80"`, ...).
  Future<void> set_({required String id, required String value});

  /// Fetch a fresh status snapshot.
  Future<BatteryStatus> status();

  /// Toggle a port or switch by id (`"ac"`, `"charging"`, `"heater"`, ...).
  Future<void> toggle({required String id, required bool on_});
}

class BatteryStatus {
  final double? soc;
  final double? soh;
  final double? voltage;
  final double? current;
  final double? powerIn;
  final double? powerOut;
  final List<Sensor> temperatures;
  final double? timeRemainingH;
  final double? capacityRemainingAh;
  final double? capacityFullAh;
  final int? cycles;
  final bool? charging;
  final bool? discharging;
  final List<Switch> switches;
  final double? chargeCurrentLimitA;
  final double? dischargeCurrentLimitA;
  final double? socLimitMax;
  final double? socLimitMin;
  final List<CellInfo> cells;
  final List<PortInfo> ports;
  final List<String> alarms;

  /// Convenience: highest reported temperature.
  final double? temperatureC;

  /// Convenience: cell voltage spread (max - min).
  final double? cellDelta;

  const BatteryStatus({
    this.soc,
    this.soh,
    this.voltage,
    this.current,
    this.powerIn,
    this.powerOut,
    required this.temperatures,
    this.timeRemainingH,
    this.capacityRemainingAh,
    this.capacityFullAh,
    this.cycles,
    this.charging,
    this.discharging,
    required this.switches,
    this.chargeCurrentLimitA,
    this.dischargeCurrentLimitA,
    this.socLimitMax,
    this.socLimitMin,
    required this.cells,
    required this.ports,
    required this.alarms,
    this.temperatureC,
    this.cellDelta,
  });

  @override
  int get hashCode =>
      soc.hashCode ^
      soh.hashCode ^
      voltage.hashCode ^
      current.hashCode ^
      powerIn.hashCode ^
      powerOut.hashCode ^
      temperatures.hashCode ^
      timeRemainingH.hashCode ^
      capacityRemainingAh.hashCode ^
      capacityFullAh.hashCode ^
      cycles.hashCode ^
      charging.hashCode ^
      discharging.hashCode ^
      switches.hashCode ^
      chargeCurrentLimitA.hashCode ^
      dischargeCurrentLimitA.hashCode ^
      socLimitMax.hashCode ^
      socLimitMin.hashCode ^
      cells.hashCode ^
      ports.hashCode ^
      alarms.hashCode ^
      temperatureC.hashCode ^
      cellDelta.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BatteryStatus &&
          runtimeType == other.runtimeType &&
          soc == other.soc &&
          soh == other.soh &&
          voltage == other.voltage &&
          current == other.current &&
          powerIn == other.powerIn &&
          powerOut == other.powerOut &&
          temperatures == other.temperatures &&
          timeRemainingH == other.timeRemainingH &&
          capacityRemainingAh == other.capacityRemainingAh &&
          capacityFullAh == other.capacityFullAh &&
          cycles == other.cycles &&
          charging == other.charging &&
          discharging == other.discharging &&
          switches == other.switches &&
          chargeCurrentLimitA == other.chargeCurrentLimitA &&
          dischargeCurrentLimitA == other.dischargeCurrentLimitA &&
          socLimitMax == other.socLimitMax &&
          socLimitMin == other.socLimitMin &&
          cells == other.cells &&
          ports == other.ports &&
          alarms == other.alarms &&
          temperatureC == other.temperatureC &&
          cellDelta == other.cellDelta;
}

/// Flattened capability flags (Dart-friendly booleans).
class Caps {
  final bool readBasic;
  final bool readCells;
  final bool readPorts;
  final bool readTemperature;
  final bool readLimits;
  final bool readAlarms;
  final bool togglePorts;
  final bool toggleCharge;
  final bool toggleDischarge;
  final bool toggleBalancer;
  final bool setChargeLimit;
  final bool writeSettings;
  final bool controllable;

  const Caps({
    required this.readBasic,
    required this.readCells,
    required this.readPorts,
    required this.readTemperature,
    required this.readLimits,
    required this.readAlarms,
    required this.togglePorts,
    required this.toggleCharge,
    required this.toggleDischarge,
    required this.toggleBalancer,
    required this.setChargeLimit,
    required this.writeSettings,
    required this.controllable,
  });

  @override
  int get hashCode =>
      readBasic.hashCode ^
      readCells.hashCode ^
      readPorts.hashCode ^
      readTemperature.hashCode ^
      readLimits.hashCode ^
      readAlarms.hashCode ^
      togglePorts.hashCode ^
      toggleCharge.hashCode ^
      toggleDischarge.hashCode ^
      toggleBalancer.hashCode ^
      setChargeLimit.hashCode ^
      writeSettings.hashCode ^
      controllable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Caps &&
          runtimeType == other.runtimeType &&
          readBasic == other.readBasic &&
          readCells == other.readCells &&
          readPorts == other.readPorts &&
          readTemperature == other.readTemperature &&
          readLimits == other.readLimits &&
          readAlarms == other.readAlarms &&
          togglePorts == other.togglePorts &&
          toggleCharge == other.toggleCharge &&
          toggleDischarge == other.toggleDischarge &&
          toggleBalancer == other.toggleBalancer &&
          setChargeLimit == other.setChargeLimit &&
          writeSettings == other.writeSettings &&
          controllable == other.controllable;
}

class CellInfo {
  final int index;
  final double? voltage;
  final double? resistance;
  final bool? balancing;

  const CellInfo({
    required this.index,
    this.voltage,
    this.resistance,
    this.balancing,
  });

  @override
  int get hashCode =>
      index.hashCode ^
      voltage.hashCode ^
      resistance.hashCode ^
      balancing.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CellInfo &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          voltage == other.voltage &&
          resistance == other.resistance &&
          balancing == other.balancing;
}

enum DeviceClass { bms, powerStation, monitor }

class DeviceInfo {
  final String backend;
  final String? model;
  final String? serial;
  final String? firmware;

  const DeviceInfo({
    required this.backend,
    this.model,
    this.serial,
    this.firmware,
  });

  @override
  int get hashCode =>
      backend.hashCode ^ model.hashCode ^ serial.hashCode ^ firmware.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceInfo &&
          runtimeType == other.runtimeType &&
          backend == other.backend &&
          model == other.model &&
          serial == other.serial &&
          firmware == other.firmware;
}

class DiscoveredDevice {
  final String id;
  final String label;
  final String backend;
  final DeviceClass class_;

  const DiscoveredDevice({
    required this.id,
    required this.label,
    required this.backend,
    required this.class_,
  });

  @override
  int get hashCode =>
      id.hashCode ^ label.hashCode ^ backend.hashCode ^ class_.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiscoveredDevice &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          backend == other.backend &&
          class_ == other.class_;
}

enum PortDirection { in_, out, bidir }

class PortInfo {
  final String id;
  final String? label;
  final PortDirection? direction;
  final bool? on_;
  final double? watts;

  const PortInfo({
    required this.id,
    this.label,
    this.direction,
    this.on_,
    this.watts,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      label.hashCode ^
      direction.hashCode ^
      on_.hashCode ^
      watts.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PortInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          direction == other.direction &&
          on_ == other.on_ &&
          watts == other.watts;
}

class Sensor {
  final String id;
  final String? label;
  final double celsius;

  const Sensor({required this.id, this.label, required this.celsius});

  @override
  int get hashCode => id.hashCode ^ label.hashCode ^ celsius.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Sensor &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          celsius == other.celsius;
}

class Switch {
  final String id;
  final String? label;
  final bool on_;

  const Switch({required this.id, this.label, required this.on_});

  @override
  int get hashCode => id.hashCode ^ label.hashCode ^ on_.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Switch &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          on_ == other.on_;
}
